sonar.projectKey=Ayush-00-hui_Territory-Runner-Game
sonar.organization=ayush-00-hui
sonar.projectName=Territory-Runner-Game
sonar.sources=lib
sonar.tests=test
sonar.exclusions=assets/**,scripts/**,android/**,ios/**,web/**,windows/**,macos/**,linux/**,test/**,**/*.json,**/*.example,**/*.png,**/*.jpg
sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=**/*
