sonar.projectKey=Ayush-00-hui_Territory-Runner-Game
sonar.organization=ayush-00-hui
sonar.projectName=Territory-Runner-Game
sonar.sources=lib
sonar.tests=test
sonar.exclusions=assets/**,scripts/**,android/**,ios/**,web/**,windows/**,macos/**,linux/**,**/*.json,**/*.example,**/*.g.dart,**/*.freezed.dart,**/*.cc,**/*.h,**/*.swift,**/*.cmake
sonar.coverage.exclusions=**/*,lib/**,test/**
sonar.cpd.exclusions=**/*,lib/**,test/**
sonar.dart.lcov.reportPath=coverage/lcov.info
sonar.qualitygate.wait=false

