sonar.projectKey=Ayush-00-hui_Territory-Runner-Game
sonar.organization=ayush-00-hui
sonar.projectName=Territory-Runner-Game
sonar.sources=lib
sonar.exclusions=**/*
sonar.test.exclusions=**/*
sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=**/*
